config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'  
  
  resources :wallets, param: :id, only: [:show] do
    resources :transactxns, only: [:index]
    get :deposit, on: :member
    patch :make_deposit, on: :member
    get :withdrawal, on: :member
    patch :make_withdrawal, on: :member
    get :transfer, on: :member
    patch :make_transfer, on: :member
    get :get_funding_sources, on: :member
    get :store_funding_sources, on: :member
    get :check_pending_transactions, on: :member
    resources :funding_sources, except: [:show, :destroy]
  end
  resources :users, only: [:index, :edit, :update] do
    resources :wallets, only: [:new, :create, :destroy, :edit, :update]
  end
  
  get 'wallets/:id/authenticate' => "wallets#authenticate", as: :wallet_authenticate
  get 'wallets/:id/activate' => "wallets#activate", as: :wallet_activate
  post 'notifications/status' => "notifications#transaction_status", as: :transaction_status 
  get 'wallets/:wallet_id/transactxn/:id' => "transactxns#show", as: :show_transaction
  
  

  devise_for :users
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :timeout_in => 15.minutes 

  validates :name, presence: true
  
  has_one :wallet, dependent: :destroy
  
  default_scope { order(created_at: :desc) }
  scope :excluding_user_by_email, -> (user_email) { where.not(email: user_email)  } 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  respond_to :html
  
  def index
    @users = User.all.paginate(pagination_size(Paginable::USER_MAX_PER_PAGE))
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :admin)
    end
  
    def set_user_recipient
      @user = current_user
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def wallet_status(user)
    user.wallet.nil? ? 'Not activated' : (user.wallet.active) ? 'Activated' : 'Deactivated'
  end
end

app/views/users/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  <p><h4><strong>Set admin role</strong></h4><p>
  </div> 
  <div class="panel-body">
<%= form_for(@user, html: {id: 'set_admin_role'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user %>
    <%= f.text_field :name, disabled: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box :admin,  :autofocus => true %> <%= f.label "Set to admin role" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Back', users_path, class: "btn btn-link" %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="center"><p><h3><strong>Manage Admin Role and Wallet</strong></h3></p></div>
<br/>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="center">User</th>
      <th class="center">Is admin role?</th>
      <th class="center">Wallet Status</th>
      <th class="center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>  
        <td><div class="center"><%= user.admin %></div></td>
        <td><div class="center"><%= wallet_status(user) %><div></td>
      <td>
        <div class="center">
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Set user admin role', edit_user_path(user), class: "btn btn-link" %></li>
            <% if user.wallet.nil? %>
            <li><%= link_to "Activate wallet", new_user_wallet_path(user), class: "btn btn-link" %></li>
            <% end %>
            <% if user.wallet.present? %>
              <% if user.wallet.active? %>
            <li><%= link_to "Deactivate wallet", edit_user_wallet_path(user,user.wallet), class: "btn btn-link" %></li>
              <% else %>
            <li><%= link_to "Reactivate wallet", edit_user_wallet_path(user,user.wallet), class: "btn btn-link" %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
        </div>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<div class="center">
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>
<br/>