config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'  
  
  resources :wallets, param: :id, only: [:show] do
    resources :transactxns, only: [:index]
    get :deposit, on: :member
    patch :make_deposit, on: :member
    get :withdrawal, on: :member
    patch :make_withdrawal, on: :member
    get :transfer, on: :member
    patch :make_transfer, on: :member
    get :get_funding_sources, on: :member
    get :store_funding_sources, on: :member
    get :check_pending_transactions, on: :member
    resources :funding_sources, except: [:show, :destroy]
  end
  resources :users, only: [:index, :edit, :update] do
    resources :wallets, only: [:new, :create, :destroy, :edit, :update]
  end
  
  get 'wallets/:id/authenticate' => "wallets#authenticate", as: :wallet_authenticate
  get 'wallets/:id/activate' => "wallets#activate", as: :wallet_activate
  post 'notifications/status' => "notifications#transaction_status", as: :transaction_status 
  get 'wallets/:wallet_id/transactxn/:id' => "transactxns#show", as: :show_transaction
  
  

  devise_for :users
  

end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
  enum acct_type: {Personal: 1, Commercial: 2}
  
  belongs_to :user
  has_many :transactxns, dependent: :destroy
  has_many :funding_sources, dependent: :destroy
  
  validates :balance, :credits, :debits, numericality: {
    greater_than_or_equal_to: 0,
    message: "can only be positive greater than 0"
    }
  
end

app/controllers/wallets_controller.rb
require 'bigdecimal'
require 'bigdecimal/util'

#require 'dwolla/account_info_scope'

class WalletsController < ApplicationController
  before_action :set_user, only: [:new, :create, :edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :authenticate, :activate, :destroy, :deposit, :make_deposit, :withdrawal, :make_withdrawal, :transfer, :make_transfer, :check_pending_transactions]
  before_action :set_wallet, only: [:show, :edit, :update, :destroy, :authenticate, :activate, :deposit, :make_deposit, :withdrawal, :make_withdrawal, :transfer, :make_transfer, :check_pending_transactions]
  before_action :checkValidTargetWallet, only: [:make_transfer]
  before_action :checkBalanceAvailable, only: [:make_transfer, :make_withdrawal]
#  before_action :set_wallet_state, only: [ :deposit, :withdrawal, :transfer ]
  before_action :set_transfer_transaction, only: [ :transfer ]
  before_action :set_transfer_transaction_with_params, only: [ :make_transfer]
  before_action :set_deposit_withdrawal_transaction, only: [:deposit, :withdrawal]
  before_action :set_deposit_withdrawal_transaction_with_params, only: [:make_deposit, :make_withdrawal]
  before_action :get_funding_sources, only: [:deposit, :withdrawal]
  
  respond_to :html

  def authenticate
    session[:wallet_state] = :update
    wallet_service = WalletService.new(@wallet, flash)
    oauth_url = wallet_service.authenticate wallet_activate_url
    logger.info "******* Dwolla url is #{oauth_url}"
    redirect_to oauth_url
  end

  def activate
    code = wallet_params[:code]
    wallet_service = WalletService.new(@wallet, flash)
    wallet_service.activate code, wallet_activate_url
    redirect_to wallet_path(@wallet)
  end

  def new 
    @wallet = Wallet.new
    session[:wallet_state] = :create
  end
  
  def edit
    session[:wallet_state] = :edit    
  end
  
  def show
    @pending_transactions = @wallet.transactxns.by_pending_txns
    @transactions = @wallet.transactxns.all.by_not_pending_txns.paginate(pagination_size(Paginable::TRANSACTION_MAX_PER_PAGE))
    @txn_types = Transactxn.txn_types
  end
  
  def create
    @wallet = Wallet.new(wallet_params)
    @wallet.user_id = @user.id
    wallet_service = WalletService.new(@wallet, flash)
    if wallet_service.create(@user.email)
      redirect_to users_path 
    else
      render :new
    end
  end

  def update
#    @wallet.active = false
    @wallet.active = params[:wallet][:active]
    @wallet.save
    redirect_to users_path   
  end

  def destroy
  end

  def deposit
    session[:wallet_state] = :deposit
  end
  
  def make_deposit 
    if @wallet_txn.valid?
      deposit_amount = wallet_params[:amount].to_d
      funding_source = FundingSource.find(wallet_params[:funding_source])
      pin = wallet_params[:pin]
      wallet_service = WalletService.new(@wallet, flash)
      begin
        wallet_service.deposit deposit_amount, funding_source, pin
        msg = "Deposit #{number_to_currency(deposit_amount)} from #{funding_source.name.strip}"
        wallet_service.log_info msg
      rescue WalletServiceException
        msg = "Failed to deposit #{number_to_currency(deposit_amount)} to #{funding_source.name.strip}"
        wallet_service.log_warning msg
      end
      redirect_to wallet_path(@wallet)
    else
      get_funding_sources
      render :deposit
    end
  end

  def withdrawal
    session[:wallet_state] = :withdrawal
  end

  def make_withdrawal
    if @wallet_txn.valid?
      withdrawal_amount = wallet_params[:amount].to_d
      funding_source = FundingSource.find(wallet_params[:funding_source])
      pin = wallet_params[:pin]
      wallet_service = WalletService.new(@wallet, flash)
      begin
        wallet_service.withdraw withdrawal_amount, funding_source, pin
        msg = "Withdraw #{number_to_currency(withdrawal_amount)} to #{funding_source.name.strip}"
        wallet_service.log_info msg
      rescue WalletServiceException
        smsg = "Failed to withdraw #{number_to_currency(withdrawal_amount)} from #{funding_source.name.strip}"
        wallet_service.log_warning msg
      end
      redirect_to wallet_path(@wallet)
    else
      get_funding_sources
      render :withdrawal
    end
  end

  def transfer
    session[:wallet_state] = :transfer
  end

  def make_transfer
    if @wallet_txn.valid?
      transfer_amount = wallet_params[:amount].to_d
      pin = wallet_params[:pin]
      notes = wallet_params[:notes]
      wallet_service = WalletService.new(@wallet, flash, @target_wallet)
      begin
        wallet_service.transfer transfer_amount, notes, pin
        msg = "Transfer #{number_to_currency(transfer_amount)} to #{@target_wallet.name.strip}'s Balance"
        wallet_service.log_info msg
      rescue WalletServiceException => e
        msg = "Failed to transfer #{number_to_currency(transfer_amount)} to #{@target_wallet.name.strip}'s Balance due to #{e.message}"
        wallet_service.log_warning msg
      end
      redirect_to wallet_path(@wallet)
    else
      render :transfer
    end
  end

  def check_pending_transactions
    @pending_transactions = @wallet.transactxns.by_pending_txns
    unless @pending_transactions.blank?
      wallet_service = WalletService.new(@wallet, flash)
      wallet_service.check_pending_transactions @pending_transactions 
    end
    redirect_to wallet_path(@wallet)
  end

  private

    def set_user
      @user = User.find(params[:user_id])
    end
  
    def set_wallet
      @wallet = Wallet.find(params[:id])
      @wallet_decorator = WalletDecorator.new(@wallet)
    end

    def set_wallet_state
      session[:wallet_state] = :wallet_transaction   
    end

    def get_funding_sources
      @funding_sources = @wallet.funding_sources.by_external_accounts.verified.select(:id, :name)
    end
    
    def set_transfer_transaction
      @wallet_txn = TransferTransaction.new
    end

    def set_transfer_transaction_with_params
      @wallet_txn = TransferTransaction.new(wallet_params)  
    end

    def set_deposit_withdrawal_transaction
      @wallet_txn = DepositWithdrawalTransaction.new
    end

    def set_deposit_withdrawal_transaction_with_params
      @wallet_txn = DepositWithdrawalTransaction.new(wallet_params)    
    end

    def wallet_params
      if current_user.admin?
        case session[:wallet_state]
          when 'create'
            params.permit(:user_id)
          when 'edit'
            params.permit(:user_id, :id)
          when 'deposit', 'withdrawal'
            params.require(:deposit_withdrawal_transaction).permit(:user_id, :amount, :funding_source, :pin)
          when 'transfer'  
            params.require(:transfer_transaction).permit(:user_id, :amount, :target_email, :pin, :notes)
          else
            params.require(:wallet).permit(:user_id, :name)
        end
      else
        case session[:wallet_state]
          when 'deposit', 'withdrawal'
            params.require(:deposit_withdrawal_transaction).permit(:id, :amount, :funding_source, :pin)
          when 'transfer'  
            params.require(:transfer_transaction).permit(:user_id, :amount, :target_email, :pin, :notes)
          when 'update'
            if (params.key? :code)
              params.permit(:id, :code)
            elsif (params.key? :access_token) && (params.key? :refresh_token)
              params.permit(:access_token, :refresh_token) 
            end
          else
            params.permit(:id) if (params.key? :id)           
        end
      end  
    end

    def checkBalanceAvailable
      redirect_to wallet_path(@wallet), alert: 'Wallet balance is not sufficient to make withdrawal or transfer' unless @wallet.avail_balance >= wallet_params[:amount].to_d
    end

    def checkValidTargetWallet
      target_email = wallet_params[:target_email]
      redirect_to wallet_path(@wallet), alert: 'Transfer not allowed for your own account' unless current_user.email != target_email
      target_user = User.find_by(email: wallet_params[:target_email])
      if target_user.nil? 
        redirect_to wallet_path(@wallet), alert: 'No valid wallet found for this recipient to initiate transfer' 
      else
        if target_user.wallet.nil?
          redirect_to wallet_path(@wallet), alert: 'Wallet for this recipient not activated yet to initiate transfer'
        else
          @target_wallet = target_user.wallet
        end
      end
    end

end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_editform.html.erb
<%= form_for([@user, @wallet], url: user_wallet_path(@user,@wallet), method: :patch) do |f| %>
  <% if @wallet.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <h4><%= pluralize(@wallet.errors.count, "error") %> prohibited this wallet from being activated:</h4>

      <ul>
      <% @wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.check_box :active,  :autofocus => true %> <%= f.label "Active" %>
  </div>

  <div class="form-group">
    <% if @wallet.active %>
    <%= f.submit value: 'Deactivate wallet', class: "btn btn-primary" %>
    <% else %>
    <%= f.submit value: 'Activate wallet', class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/wallets/_newform.html.erb
<%= form_for([@user, @wallet], url: user_wallets_path(@user)) do |f| %>
  <% if @wallet.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <h4><%= pluralize(@wallet.errors.count, "error") %> prohibited this wallet from being activated:</h4>

      <ul>
      <% @wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_area :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit value: 'Activate wallet', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/wallets/deposit.html.erb
<div class="panel panel-default">

  <div class="panel-heading">

<p><h4><strong>Add to <%= @wallet_decorator.name %> Wallet No. <%= @wallet_decorator.display_wallet_id %></strong></h4><p>
  </div> 
    <div class="panel-body">

<%= form_for(@wallet_txn, url: make_deposit_wallet_path(@wallet), method: :patch, html: {id: 'make_deposit'}) do |f| %>
  <% if @wallet_txn.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <h4><%= pluralize(@wallet_txn.errors.count, "error") %> prohibited to deposit to this wallet:</h4>

      <ul>
        <% @wallet_txn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :amount_to_add %>
    <%= f.number_field :amount, class: "form-control", placeholder: 'Enter amount...' %>
  </div>
  <div class="form-group">
    <%= f.label :from_account %><br/>
    <%= f.collection_select :funding_source, @funding_sources, :id, :name, {prompt: "Choose bank account"}, class: "btn btn-default dropdown-toggle" %>
  </div>
  <div class="form-group">
    <%= f.label :pin %>
    <%= f.password_field :pin, class: "form-control", placeholder: 'Enter pin...' %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary", value: "Add" %>
  </div>
<% end %>
  </div>
  <div class="panel-footer">
<%= link_to "Back", wallet_path, class: "btn btn-link" %>
  </div>
</div>

app/views/wallets/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <p><h4><strong>Wallet for <%= @user.name %></strong></h4></p>
  </div> 
  <div class="panel-body">
    <%= render 'editform' %>
  </div>
  <div class="panel-footer">    
    <%= link_to 'Back', :back %>
  </div>
</div>

app/views/wallets/index.html.erb
<h1>Listing wallets</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Balance</th>
      <th>Credits</th>
      <th>Debits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallets.each do |wallet| %>
      <tr>
        <td><%= wallet.description %></td>
        <td><%= wallet.balance %></td>
        <td><%= wallet.credits %></td>
        <td><%= wallet.debits %></td>
        <td><%= link_to 'Show', wallet %></td>
        <td><%= link_to 'Edit', edit_wallet_path(wallet) %></td>
        <td><%= link_to 'Destroy', wallet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wallet', new_wallet_path %>

app/views/wallets/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <p><h4><strong>Wallet for <%= @user.name %></strong></h4></p>
  </div> 
  <div class="panel-body">
    <%= render 'newform' %>
  </div>
  <div class="panel-footer">    
    <%= link_to 'Back', :back %>
  </div>
</div>

app/views/wallets/show.html.erb
<%= render 'transactxns/transactions' %>

app/views/wallets/transfer.html.erb
<div class="panel panel-default">

  <div class="panel-heading">

<p><h4><strong>Send from <%= @wallet_decorator.name %> Wallet No. <%= @wallet_decorator.display_wallet_id %></strong></h4><p>
  </div> 
    <div class="panel-body">
  
<%= form_for(@wallet_txn, url: make_transfer_wallet_path(@wallet), method: :patch, html: {id: 'make_transfer'}) do |f| %>
<% if @wallet_txn.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <h4><%= pluralize(@wallet_txn.errors.count, "error") %> prohibited to transfer from this wallet:</h4>

      <ul>
        <% @wallet_txn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :amount_to_send %>
    <%= f.number_field :amount, class: "form-control", placeholder: 'Enter amount...' %>
  </div>

  <div class="form-group">
    <%= f.label :to_recipient %>
    <%= f.email_field :target_email, class: "form-control", placeholder: "Enter recipient's email..." %>
  </div>
  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: "form-control", placeholder: "Enter notes..." %>
  </div>
  <div class="form-group">
    <%= f.label :pin %>
    <%= f.password_field :pin, class: "form-control", placeholder: 'Enter pin...' %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary", value: "Send" %>
  </div>
<% end %>
  </div>
  <div class="panel-footer">
<%= link_to "Back", wallet_path, class: "btn btn-link" %>
  </div>
</div>

app/views/wallets/withdrawal.html.erb
<div class="panel panel-default">

  <div class="panel-heading">

<p><h4><strong>Withdrawal from <%= @wallet_decorator.name %> Wallet No. <%= @wallet_decorator.display_wallet_id %></strong></h4><p>
  </div> 
    <div class="panel-body">
  
<%= form_for(@wallet_txn, url: make_withdrawal_wallet_path(@wallet), method: :patch, html: {id: 'make_withdrawal'}) do |f| %>
<% if @wallet_txn.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <h4><%= pluralize(@wallet_txn.errors.count, "error") %> prohibited to withdraw from this wallet:</h4>

      <ul>
        <% @wallet_txn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :amount_to_withdraw %>
    <%= f.number_field :amount, class: "form-control", placeholder: 'Enter amount...' %>
  </div>
  <div class="form-group">
    <%= f.label :to_account %><br/>
    <%= f.collection_select :funding_source, @funding_sources, :id, :name, {prompt: "Choose bank account"}, class: "btn btn-default dropdown-toggle" %>
  </div>
  <div class="form-group">
    <%= f.label :pin %>
    <%= f.password_field :pin, class: "form-control", placeholder: 'Enter pin...' %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary", value: "Withdraw" %>
  </div>
<% end %>
  </div>
  <div class="panel-footer">

<%= link_to "Back", wallet_path, class: "btn btn-link" %>
  </div>
</div>