config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'  
  
  resources :wallets, param: :id, only: [:show] do
    resources :transactxns, only: [:index]
    get :deposit, on: :member
    patch :make_deposit, on: :member
    get :withdrawal, on: :member
    patch :make_withdrawal, on: :member
    get :transfer, on: :member
    patch :make_transfer, on: :member
    get :get_funding_sources, on: :member
    get :store_funding_sources, on: :member
    get :check_pending_transactions, on: :member
    resources :funding_sources, except: [:show, :destroy]
  end
  resources :users, only: [:index, :edit, :update] do
    resources :wallets, only: [:new, :create, :destroy, :edit, :update]
  end
  
  get 'wallets/:id/authenticate' => "wallets#authenticate", as: :wallet_authenticate
  get 'wallets/:id/activate' => "wallets#activate", as: :wallet_activate
  post 'notifications/status' => "notifications#transaction_status", as: :transaction_status 
  get 'wallets/:wallet_id/transactxn/:id' => "transactxns#show", as: :show_transaction
  
  

  devise_for :users
  

end

app/models/funding_source.rb
class FundingSource < ActiveRecord::Base
  belongs_to :wallet
  
  validates_presence_of :source_id, :name
  #validates_uniqueness_of :name
  
  scope :by_external_accounts, -> { where.not(name: 'My Dwolla Balance') }
  scope :verified, -> { where(verified: true).order(name: :asc) }
  
end

app/controllers/funding_sources_controller.rb
class FundingSourcesController < ApplicationController
#  before_action :set_user, only: [:new, :create]
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_wallet, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :set_create_funding_source, only: [:new]
  before_action :set_verify_funding_source, only: [:edit, :update]
  
  respond_to :html

  def index
    @funding_sources = @wallet.funding_sources.all
    if @funding_sources.nil?
      redirect_to get_funding_sources_wallet_path(@wallet)      
    end
    @funding_sources = @funding_sources.by_external_accounts
    @wallet_decorator = WalletDecorator.new(@wallet)
  end
  
  def new 
    @types = %w(Checking Savings)
    session[:funding_source] = :add
  end
  
  def show
    
  end

  def edit
    session[:funding_source] = :verify
  end

  def create
    @funding_source = CreateFundingSource.new(funding_source_params)
    if @funding_source.valid?
      routing_no = @funding_source.routing_number
      acct_no = @funding_source.account_number
      acct_type = @funding_source.type
      acct_name = @funding_source.name
      wallet_service = WalletService.new(@wallet, flash)
      wallet_service.add_funding_source routing_no, acct_no, acct_type, acct_name
      redirect_to wallet_funding_sources_path(@wallet)
    else
      @types = %w(Checking Savings)
      render :new
    end
  end

  def update
    @funding_source = VerifyFundingSource.new(funding_source_params)
    if @funding_source.valid?
      deposit1 = funding_source_params[:deposit1]
      deposit2 = funding_source_params[:deposit2]
      funding_source_id = @wallet_funding_source.source_id
      wallet_service = WalletService.new(@wallet, flash)
      wallet_service.verify_funding_source funding_source_id, deposit1, deposit2
      redirect_to wallet_funding_sources_path(@wallet)
    else
      @wallet_funding_source = FundingSource.find(params[:id])
      render :edit
    end
  end

  def destroy
    @wallet.active = false
    @wallet.save
    redirect_to wallet_path(@wallet), notice: "Wallet is deactivated."
  end


  private

    def set_wallet
      @wallet = Wallet.find(params[:wallet_id])
      @wallet_decorator = WalletDecorator.new(@wallet)
    end

    def set_create_funding_source
      @funding_source = CreateFundingSource.new
    end
  
    def set_verify_funding_source
      logger.info "Verify funding source id is #{params[:id]}"
      @wallet_funding_source = FundingSource.find(params[:id])
      @funding_source = VerifyFundingSource.new
    end
  
    def funding_source_params
      case session[:funding_source]
        when 'add'
          params.require(:create_funding_source).permit(:name, :type, :routing_number, :account_number)
        when 'verify'  
          params.require(:verify_funding_source).permit(:id, :deposit1, :deposit2)
      end  
    end

end

app/views/funding_sources/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <p><h4><strong>Verify funding source for <%= @wallet_decorator.name %> Wallet No. <%= @wallet_decorator.display_wallet_id %> </strong></h4></p>
  </div> 
  <div class="panel-body">
<%= form_for(@funding_source, url: wallet_funding_source_path(@wallet, @wallet_funding_source), method: :patch, html: {id: 'funding_source' }) do |f| %>
  <% if @funding_source.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <h4><%= pluralize(@funding_source.errors.count, "error") %> prohibited to verify funding source:</h4>
      <ul>
      <% @funding_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :deposit1 %>
    <%= f.number_field :deposit1, class: "form-control", :placeholder => 'Enter deposit1' %>
  </div>
  <div class="form-group">
    <%= f.label :deposit2 %>
    <%= f.number_field :deposit2,  class: "form-control", :placeholder => 'Enter deposit2' %>
  </div>

  <div class="form-group">
    <%= f.submit value: "Verify funding source", class: "btn btn-primary" %>
  </div>
<% end %>
  </div>
  <div class="panel-footer">    
    <%= link_to 'Back', wallet_funding_sources_path(@wallet), class: "btn btn-link" %>
  </div>
</div>

app/views/funding_sources/index.html.erb
<div class="center"><p><h3><strong>Funding Sources for Wallet No. <%= @wallet_decorator.display_wallet_id %></strong></h3></p></div>
<br/>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="center">Name</th>
      <th class="center">Type</th>
      <th class="center">Process Type</th>
      <th class="center">Verified?</th>
      <th class="center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @funding_sources.each do |funding_source| %>
      <tr>
        <td><div class="text-left"><strong><%= funding_source.name %></strong></div></td>  
        <td><div class="center"><%= funding_source.acct_type %></div></td>
        <td><div class="center"><%= funding_source.processing_type %><div></td>
        <td><div class="center"><%= funding_source.verified %><div></td>
        <td>
          <div class="center">
          <% if  !funding_source.verified %>
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Action <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Verify funding source', edit_wallet_funding_source_path(@wallet, funding_source), class: "btn btn-link" %></li>
              </ul>
            </div>
          <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
    
  <% if @funding_sources.by_external_accounts.count < 2 %>
    <%= link_to new_wallet_funding_source_path(@wallet), class: "btn btn-primary", data: { no_turbolink: true } do %>
    <i class="glyphicon glyphicon-plus"></i> New funding source
  <% end %>
<% end %>

app/views/funding_sources/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <p><h4><strong>New funding source for <%= @wallet_decorator.name %> Wallet No. <%= @wallet_decorator.display_wallet_id %> </strong></h4></p>
  </div> 
  <div class="panel-body">
<%= form_for(@funding_source, url: wallet_funding_sources_path(@wallet), html: {id: 'funding_source' }) do |f| %>
  <% if @funding_source.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <h4><%= pluralize(@funding_source.errors.count, "error") %> prohibited to add funding source:</h4>
      <ul>
      <% @funding_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name,  class: "form-control", :placeholder => 'Enter account name'  %>
  </div>
  <div class="form-group">
    <%= f.label :type %><br/>
    <%= f.select :type, @types, {prompt: "Choose type"}, class: "btn btn-default dropdown-toggle" %>
  </div>
  <div class="form-group">
    <%= f.label :routing_number %>
    <%= f.text_field :routing_number, class: "form-control", :placeholder => '111000025' %>
  </div>
  <div class="form-group">
    <%= f.label :account_number %>
    <%= f.text_field :account_number,  class: "form-control", :placeholder => '000123456789' %>
  </div>

  <div class="form-group">
    <%= f.submit value: "Add funding source", class: "btn btn-primary" %>
  </div>
<% end %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Back', wallet_funding_sources_path(@wallet), class: "btn btn-link" %>
  </div>
</div>