config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'  
  
  resources :wallets, param: :id, only: [:show] do
    resources :transactxns, only: [:index]
    get :deposit, on: :member
    patch :make_deposit, on: :member
    get :withdrawal, on: :member
    patch :make_withdrawal, on: :member
    get :transfer, on: :member
    patch :make_transfer, on: :member
    get :get_funding_sources, on: :member
    get :store_funding_sources, on: :member
    get :check_pending_transactions, on: :member
    resources :funding_sources, except: [:show, :destroy]
  end
  resources :users, only: [:index, :edit, :update] do
    resources :wallets, only: [:new, :create, :destroy, :edit, :update]
  end
  
  get 'wallets/:id/authenticate' => "wallets#authenticate", as: :wallet_authenticate
  get 'wallets/:id/activate' => "wallets#activate", as: :wallet_activate
  post 'notifications/status' => "notifications#transaction_status", as: :transaction_status 
  get 'wallets/:wallet_id/transactxn/:id' => "transactxns#show", as: :show_transaction
  
  

  devise_for :users
  

end

app/views/layouts/_footer.html.erb
<br/>
<div class="center">
  <p><strong>Copyright <i class="glyphicon glyphicon-copyright-mark"></i> 2014-2021 Wally<em>Pay</em></strong> by <strong>Daniel Ha</strong><br/>
    <strong>Powered by</strong><br/> 
    <strong>Rails <%= Rails::VERSION::STRING %> and Bootstrap 3.4.1</strong></p>
   <%= social_share_button_tag("WallyPay", :url => "http://wallypay.herokuapp.com") %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Wally<em>Pay</em></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <% if current_user.admin? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Settings <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to users_path do %>
              <i class="glyphicon glyphicon-user"></i> Manage Admin Role and Wallet
              <% end %>              
            </li>
          </ul>
        </li>
      <% end %>
      <% if !current_user.wallet.nil? && current_user.wallet.active && current_user.wallet.token.present?%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to wallet_path(current_user.wallet), data: { no_turbolink: true } do %>
              <i class="glyphicon glyphicon-book"></i> Summary
              <% end %>              
            </li>
            <li><%= link_to deposit_wallet_path(current_user.wallet) do %>
              <i class="glyphicon glyphicon-plus"></i> Add
              <% end %>             
            </li>
            <% if current_user.wallet.avail_balance > 0 %>
            <li><%= link_to withdrawal_wallet_path(current_user.wallet) do %>
              <i class="glyphicon glyphicon-minus"></i> Withdraw
              <% end %>              
            </li>

            <li><%= link_to transfer_wallet_path(current_user.wallet), data: { no_turbolink: true } do %>
              <i class="glyphicon glyphicon-random"></i> Send
              <% end %>              
            </li>
            <% end %>

          </ul>
        </li>
      <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to edit_user_registration_path do %>
              <i class="glyphicon glyphicon-edit"></i> Edit Profile
              <% end %>   
            </li>
            <% if current_user.wallet.present? && current_user.wallet.active %>
            <% if current_user.wallet.token.nil? %>
            <li><%= link_to wallet_authenticate_path(current_user.wallet) do %>
              <i class="glyphicon glyphicon-book"></i> Activate Wallet
              <% end %>   
            </li> 
            <% end %>
            <% if current_user.wallet.token.present? %>
            <li><%= link_to wallet_funding_sources_path(current_user.wallet), data: { no_turbolink: true } do %>
              <i class="glyphicon glyphicon-book"></i> Get Funding Sources
              <% end %>              
            </li>
            <% end %>
            <% if !current_user.wallet.transactxns.by_pending_txns.blank? %>
            <li><%= link_to check_pending_transactions_wallet_path(current_user.wallet), data: { no_turbolink: true } do %>
              <i class="glyphicon glyphicon-check"></i> Check Pending Transactions
              <% end %>              
            </li>
            <% end %>
            <% end %>

            <li><%= link_to destroy_user_session_path, method: :delete do %>
              <i class="glyphicon glyphicon-log-out"></i> Sign Out
              <% end %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to new_user_registration_path do %>
              <i class="glyphicon glyphicon-user"></i> Sign Up
            <% end %>
        </li>
        <li><%= link_to  new_user_session_path do %>
              <i class="glyphicon glyphicon-log-in"></i> Login
            <% end %>
        </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WallyPay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  </div>
  
  <%= javascript_tag do %>
     $(function() {
       $("time.timeago").timeago();
     });
  <% end %>  
</body>
</html>